# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'introduction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(QtWidgets.QMainWindow):
    def setupUi(self):
        self.setObjectName("Form")
        self.resize(581, 399)
        self.tabWidgetIntroduction = QtWidgets.QTabWidget(self)
        self.tabWidgetIntroduction.setObjectName("tabWidgetIntroduction")
        
        self.tab_welcome = QtWidgets.QWidget()
        self.tab_welcome.setObjectName("tab_welcome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_welcome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextEditWelcome = QtWidgets.QPlainTextEdit(self.tab_welcome)
        self.TextEditWelcome.setObjectName("TextEditWelcome")
        self.gridLayout_2.addWidget(self.TextEditWelcome, 1, 0, 1, 1)
        self.WelcomeImg = QtWidgets.QLabel(self.tab_welcome)
        self.WelcomeImg.setText("")
        self.WelcomeImg.setPixmap(QtGui.QPixmap(":/Introduction1/welcome.gif"))
        self.WelcomeImg.setObjectName("WelcomeImg")
        self.gridLayout_2.addWidget(self.WelcomeImg, 2, 0, 1, 1)
        self.tabWidgetIntroduction.addTab(self.tab_welcome, "")
        self.tab_programming = QtWidgets.QWidget()
        self.tab_programming.setObjectName("tab_programming")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_programming)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TextEditProgramming = QtWidgets.QPlainTextEdit(self.tab_programming)
        self.TextEditProgramming.setObjectName("TextEditProgramming")
        self.gridLayout_3.addWidget(self.TextEditProgramming, 0, 0, 1, 1)
        self.ProgrammingImg = QtWidgets.QLabel(self.tab_programming)
        self.ProgrammingImg.setText("")
        self.ProgrammingImg.setPixmap(QtGui.QPixmap(":/Introduction1/programowanie.gif"))
        self.ProgrammingImg.setObjectName("ProgrammingImg")
        self.gridLayout_3.addWidget(self.ProgrammingImg, 1, 0, 1, 1)
        self.tabWidgetIntroduction.addTab(self.tab_programming, "")
        self.tab_algorithm = QtWidgets.QWidget()
        self.tab_algorithm.setObjectName("tab_algorithm")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_algorithm)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TextEditAlgorithm = QtWidgets.QPlainTextEdit(self.tab_algorithm)
        self.TextEditAlgorithm.setObjectName("TextEditAlgorithm")
        self.gridLayout_4.addWidget(self.TextEditAlgorithm, 0, 0, 1, 1)
        self.AlgorithmImg = QtWidgets.QLabel(self.tab_algorithm)
        self.AlgorithmImg.setText("")
        self.AlgorithmImg.setPixmap(QtGui.QPixmap(":/Introduction1/algorytm.gif"))
        self.AlgorithmImg.setObjectName("AlgorithmImg")
        self.gridLayout_4.addWidget(self.AlgorithmImg, 1, 0, 1, 1)
        self.tabWidgetIntroduction.addTab(self.tab_algorithm, "")
        self.tab_console = QtWidgets.QWidget()
        self.tab_console.setObjectName("tab_console")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_console)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TextEditConsole = QtWidgets.QPlainTextEdit(self.tab_console)
        self.TextEditConsole.setObjectName("TextEditConsole")
        self.gridLayout_5.addWidget(self.TextEditConsole, 0, 0, 1, 1)
        self.ConsoleImg = QtWidgets.QLabel(self.tab_console)
        self.ConsoleImg.setText("")
        self.ConsoleImg.setPixmap(QtGui.QPixmap(":/Introduction1/konsola.gif"))
        self.ConsoleImg.setObjectName("ConsoleImg")
        self.gridLayout_5.addWidget(self.ConsoleImg, 1, 0, 1, 1)
        self.tabWidgetIntroduction.addTab(self.tab_console, "")
        self.tab_orders = QtWidgets.QWidget()
        self.tab_orders.setObjectName("tab_orders")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_orders)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plainTextOrders = QtWidgets.QPlainTextEdit(self.tab_orders)
        self.plainTextOrders.setObjectName("plainTextOrders")
        self.gridLayout_6.addWidget(self.plainTextOrders, 0, 0, 1, 1)
        self.OrdersImg = QtWidgets.QLabel(self.tab_orders)
        self.OrdersImg.setText("")
        self.OrdersImg.setPixmap(QtGui.QPixmap(":/Introduction1/order.gif"))
        self.OrdersImg.setObjectName("OrdersImg")
        self.gridLayout_6.addWidget(self.OrdersImg, 1, 0, 1, 1)
        self.tabWidgetIntroduction.addTab(self.tab_orders, "")

        self.retranslateUi()
        self.tabWidgetIntroduction.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setCentralWidget(self.tabWidgetIntroduction)
        self.setWindowTitle(_translate("Form", "Podstawowe informacje"))
        self.TextEditWelcome.setPlainText(_translate("Form", "Witajcie drodzy ucznowie!\n"
"Przygotowałem tę aplikację, aby pomóc wam w nauce programowania. Mam nadzieję, że sprawi wam ona przyjemność i pobudzi wasze mózgi do myślenia. \n"
"Zaczniemy od całkowitych podstaw, więc bez obaw. Żadna wiedza nie jest potrzebna na start. Przedstawione tutaj materiały przeznaczone są głównie dla dzieci w wieku szkolnym, ale osoby dorosłe również mogą z nich skorzystać.\n"
"Mogę was nauczyć, jak uwięzić w butelce sławę, uwarzyć chwałę, a nawet powstrzymać śmierć... Jeśli tylko nie jesteście bandą bałwanów, jakich zwykle muszę nauczać."))
        self.tabWidgetIntroduction.setTabText(self.tabWidgetIntroduction.indexOf(self.tab_welcome), _translate("Form", "Witam!"))
        self.TextEditProgramming.setPlainText(_translate("Form", "Czym jest programowanie? \n"
"Bardzo dobre pytanie. W końcu musimy od czegoś zacząć. Programowanie to zmuszanie komputera do posłuszeństwa. W wyniku programowania otrzymujemy program - to ciąg poleceń dla komutera. Od nas tylko zależy, kiedy go uruchomimy. Jeśli program działa źle, to najprawdopodobniej nie wina komputera, tylko programistów, którzy go stworzyli.\n"
"Programy potrafią być bardzo skomplikowane, dlatego też często nie sposób uniknąć wszystkich błędów. \n"
"Pytonik to również program komputerowy. I nie jest wolny od błędów (choć niektóre mogą znajdować się tam celowo)."))
        self.tabWidgetIntroduction.setTabText(self.tabWidgetIntroduction.indexOf(self.tab_programming), _translate("Form", "Programowanie"))
        self.TextEditAlgorithm.setPlainText(_translate("Form", "Algorytm to opisane po kolei kroki potrzebne do rozwiązania jakiegoś problemu. \n"
"Przykładem algorytmu będzie przepis na ciasto. Będziemy potrzebowali jakiś składników. Następnie trzeba wykonać pewne kroki, żeby ostatecznie otrzymać nasze ciasto. \n"
"Tylko tutaj będziemy dużo częściej doczynienia z matematycznymi przekształceniami. To tyle z pieczenia ciasta."))
        self.tabWidgetIntroduction.setTabText(self.tabWidgetIntroduction.indexOf(self.tab_algorithm), _translate("Form", "Algorytm"))
        self.TextEditConsole.setPlainText(_translate("Form", "I wcale nie chodzi tutaj o konsole do gry!\n"
"Pierwsze nasze programy tam właśnie będą odtwarzane. Nie będą miały żadnego interfejsu graficznego. Będziemy jedynie wpisywali dane i otrzymywali wyniki - efekty graficzne będą bardzo ograniczone. Tak każdy zaczynał. Trzeba zrozumieć podstawy, aby móc później zostać ekspertem.\n"
"Jeśli jesteście uważni, to jedną konsole mogliście już zauważyć, która otworzyła jednocześnie z naszą aplikacją. Jest praktycznie cała czarna, a po otworzeniu tej zakładki pojawił się tam tekst. Sprawdźcie sami, jeśli nie wierzycie!"))
        self.tabWidgetIntroduction.setTabText(self.tabWidgetIntroduction.indexOf(self.tab_console), _translate("Form", "Konsola"))
        self.plainTextOrders.setPlainText(_translate("Form", "Aby stworzyć program musimy przekazać komputerowi jakieś instrukcję (co ma robić), czyli inaczej rozkazy. Może to być na przykład - dodaj dwie liczby i wynik pomnóż razy cztery.  \n"
"Żeby komputer zrozumiał nasze rozkazy będziemy musieli zapisywać je w odpowiedni sposób - w zrozumiałym dla niego języku. Tak, dobrze usłyszałeś, komputery mają swój własny język, którego będziemy musieli się nauczyć, aby się z nimi porozumieć.\n"
"Co więcej komputery przeważnie nie będą się zastanawiały nad sensownością naszych rozkazów. Będą je wykonywały jeden po drugim zgodnie z tym jak je rozplanujemy. To do nas leży weryfikacja, czy komputerowi uda się osiągnąć zamierzony cel, jeśli będzie podążął według stworzonego przez nas planu."))
        self.tabWidgetIntroduction.setTabText(self.tabWidgetIntroduction.indexOf(self.tab_orders), _translate("Form", "Rozkazy"))
import obrazki.obrazki_introduction


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_Form()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
