# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variables.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(649, 512)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidgetVariables = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetVariables.setObjectName("tabWidgetVariables")
        self.tab_welcome = QtWidgets.QWidget()
        self.tab_welcome.setObjectName("tab_welcome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_welcome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TextEditWelcomeVariables = QtWidgets.QPlainTextEdit(self.tab_welcome)
        self.TextEditWelcomeVariables.setObjectName("TextEditWelcomeVariables")
        self.gridLayout_2.addWidget(self.TextEditWelcomeVariables, 2, 0, 1, 1)
        self.WelcomeVariablesImg = QtWidgets.QLabel(self.tab_welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WelcomeVariablesImg.sizePolicy().hasHeightForWidth())
        self.WelcomeVariablesImg.setSizePolicy(sizePolicy)
        self.WelcomeVariablesImg.setText("")
        self.WelcomeVariablesImg.setPixmap(QtGui.QPixmap(":/variables/orders_intro.gif"))
        self.WelcomeVariablesImg.setObjectName("WelcomeVariablesImg")
        self.gridLayout_2.addWidget(self.WelcomeVariablesImg, 5, 0, 1, 1)
        self.tabWidgetVariables.addTab(self.tab_welcome, "")
        self.tab_variables_names = QtWidgets.QWidget()
        self.tab_variables_names.setObjectName("tab_variables_names")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_variables_names)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.VariablesNamesImg = QtWidgets.QLabel(self.tab_variables_names)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VariablesNamesImg.sizePolicy().hasHeightForWidth())
        self.VariablesNamesImg.setSizePolicy(sizePolicy)
        self.VariablesNamesImg.setMinimumSize(QtCore.QSize(0, 200))
        self.VariablesNamesImg.setMaximumSize(QtCore.QSize(556, 220))
        self.VariablesNamesImg.setText("")
        self.VariablesNamesImg.setPixmap(QtGui.QPixmap(":/variables/home_change.png"))
        self.VariablesNamesImg.setObjectName("VariablesNamesImg")
        self.gridLayout_3.addWidget(self.VariablesNamesImg, 1, 0, 1, 1)
        self.TextEditVariablesNames = QtWidgets.QPlainTextEdit(self.tab_variables_names)
        self.TextEditVariablesNames.setMinimumSize(QtCore.QSize(0, 188))
        self.TextEditVariablesNames.setObjectName("TextEditVariablesNames")
        self.gridLayout_3.addWidget(self.TextEditVariablesNames, 0, 0, 1, 1)
        self.tabWidgetVariables.addTab(self.tab_variables_names, "")
        self.tab_set_value = QtWidgets.QWidget()
        self.tab_set_value.setObjectName("tab_set_value")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_set_value)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TextEditSetValue = QtWidgets.QPlainTextEdit(self.tab_set_value)
        self.TextEditSetValue.setMinimumSize(QtCore.QSize(0, 0))
        self.TextEditSetValue.setObjectName("TextEditSetValue")
        self.gridLayout_4.addWidget(self.TextEditSetValue, 0, 0, 1, 1)
        self.SetValueImg = QtWidgets.QLabel(self.tab_set_value)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetValueImg.sizePolicy().hasHeightForWidth())
        self.SetValueImg.setSizePolicy(sizePolicy)
        self.SetValueImg.setMinimumSize(QtCore.QSize(0, 0))
        self.SetValueImg.setMaximumSize(QtCore.QSize(16777215, 250))
        self.SetValueImg.setText("")
        self.SetValueImg.setPixmap(QtGui.QPixmap(":/variables/variableValues.png"))
        self.SetValueImg.setObjectName("SetValueImg")
        self.gridLayout_4.addWidget(self.SetValueImg, 1, 0, 1, 1)
        self.tabWidgetVariables.addTab(self.tab_set_value, "")
        self.tab_get_value = QtWidgets.QWidget()
        self.tab_get_value.setObjectName("tab_get_value")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_get_value)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TextEditGetValue = QtWidgets.QPlainTextEdit(self.tab_get_value)
        self.TextEditGetValue.setMinimumSize(QtCore.QSize(0, 0))
        self.TextEditGetValue.setObjectName("TextEditGetValue")
        self.gridLayout_5.addWidget(self.TextEditGetValue, 0, 0, 1, 2)
        self.GetValueImg = QtWidgets.QLabel(self.tab_get_value)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GetValueImg.sizePolicy().hasHeightForWidth())
        self.GetValueImg.setSizePolicy(sizePolicy)
        self.GetValueImg.setMinimumSize(QtCore.QSize(0, 0))
        self.GetValueImg.setMaximumSize(QtCore.QSize(16777215, 250))
        self.GetValueImg.setText("")
        self.GetValueImg.setPixmap(QtGui.QPixmap(":/variables/clown-box.jpg"))
        self.GetValueImg.setObjectName("GetValueImg")
        self.gridLayout_5.addWidget(self.GetValueImg, 1, 0, 2, 2)
        self.tabWidgetVariables.addTab(self.tab_get_value, "")
        self.tab_exercise1 = QtWidgets.QWidget()
        self.tab_exercise1.setObjectName("tab_exercise1")
        self.pushButtonReady1 = QtWidgets.QPushButton(self.tab_exercise1)
        self.pushButtonReady1.setGeometry(QtCore.QRect(220, 280, 131, 23))
        self.pushButtonReady1.setObjectName("pushButtonReady1")
        self.lineEditExercise1 = QtWidgets.QLineEdit(self.tab_exercise1)
        self.lineEditExercise1.setGeometry(QtCore.QRect(310, 180, 311, 20))
        self.lineEditExercise1.setObjectName("lineEditExercise1")
        self.TextEditExercise1 = QtWidgets.QPlainTextEdit(self.tab_exercise1)
        self.TextEditExercise1.setGeometry(QtCore.QRect(130, 20, 371, 61))
        self.TextEditExercise1.setObjectName("TextEditExercise1")
        self.labelExercise1 = QtWidgets.QLabel(self.tab_exercise1)
        self.labelExercise1.setGeometry(QtCore.QRect(250, 350, 47, 13))
        self.labelExercise1.setText("")
        self.labelExercise1.setObjectName("labelExercise1")
        self.widget = QtWidgets.QWidget(self.tab_exercise1)
        self.widget.setGeometry(QtCore.QRect(40, 142, 191, 112))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonGrunwald = QtWidgets.QPushButton(self.widget)
        self.pushButtonGrunwald.setObjectName("pushButtonGrunwald")
        self.verticalLayout.addWidget(self.pushButtonGrunwald)
        self.pushButtonPanTadeusz = QtWidgets.QPushButton(self.widget)
        self.pushButtonPanTadeusz.setObjectName("pushButtonPanTadeusz")
        self.verticalLayout.addWidget(self.pushButtonPanTadeusz)
        self.pushButtonStolicaPolski = QtWidgets.QPushButton(self.widget)
        self.pushButtonStolicaPolski.setObjectName("pushButtonStolicaPolski")
        self.verticalLayout.addWidget(self.pushButtonStolicaPolski)
        self.pushButtonProgramowanie = QtWidgets.QPushButton(self.widget)
        self.pushButtonProgramowanie.setObjectName("pushButtonProgramowanie")
        self.verticalLayout.addWidget(self.pushButtonProgramowanie)
        self.tabWidgetVariables.addTab(self.tab_exercise1, "")
        self.tab_exercise2 = QtWidgets.QWidget()
        self.tab_exercise2.setObjectName("tab_exercise2")
        self.TextEditExercise2 = QtWidgets.QPlainTextEdit(self.tab_exercise2)
        self.TextEditExercise2.setGeometry(QtCore.QRect(110, 40, 381, 71))
        self.TextEditExercise2.setObjectName("TextEditExercise2")
        self.pushButtonRunExercise2 = QtWidgets.QPushButton(self.tab_exercise2)
        self.pushButtonRunExercise2.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.pushButtonRunExercise2.setObjectName("pushButtonRunExercise2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_exercise2)
        self.lineEdit.setGeometry(QtCore.QRect(182, 170, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidgetVariables.addTab(self.tab_exercise2, "")
        self.gridLayout.addWidget(self.tabWidgetVariables, 0, 1, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.tabWidgetVariables.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Zmienne"))
        self.TextEditWelcomeVariables.setPlainText(_translate("MainWindow", "Ciężko mówić o programowaniu bez wytłumaczenia czym są zmienne.\n"
"Sama nazwa tego pojęcia (zmienna) kojarzy nam się z jakąś zmianą czegoś. Nie będzie to jednak bardzo precyzyjne skojarzenie i lepiej nie iść tą drogą. \n"
"O wiele lepiej myśleć o zmiennej jako o pewnej skrzyni, w której będziemy przechowywali jakąś wartość (liczbę lub tekst), z którego później będziemy mogli skorzystać.\n"
"Aby ta skrzynka była nam przydatna to musi mieć unikalną nazwę. Najlepiej, aby nazwa tej zmiennej odzwierciedlała jej zawartość np. w zmiennej o nazwie wiek_psa będziemy przechowywali liczbę lat psa."))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_welcome), _translate("MainWindow", "Zmienne!"))
        self.TextEditVariablesNames.setPlainText(_translate("MainWindow", "Jak już wspominałem wcześniej każda ze zmiennych musi mieć swoją nazwę. W języku Python istnieją pewne ograniczenia dotyczące tej nazwy:\n"
"- nie mogą to być nazwy wykorzystywane już przez język Python tj. class, break, and, in, global\n"
"- nie może zawierać spacji (zamiast spacji będziemy wykorzystywali znak \"_\")\n"
"- nie może zaczynać się od liczby\n"
"- nie może zawierać znaków tj. $ , + . = \"  \' * ( ) [ ]  & ^ % # @ ! ?\n"
"\n"
"Głównym powodem ograniczeń jest fakt, iż komputer ciężko miałby zrozumieć co mamy na myśli gdybyśmy na przykład napisalibyśmy a+b - chodziło mi o dodawanie tych dwóch zmiennych a i b, a może chciałem nazwać nową zmienną a+b.\n"
"\n"
"Przykładami dobrych nazw zmiennych są: age, name, pets_count, number1, number2.\n"
"Przykłady złych nazw zmiennych: 123, 1number, name$, first name, break"))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_variables_names), _translate("MainWindow", "Nazwy zmiennych"))
        self.TextEditSetValue.setPlainText(_translate("MainWindow", "Skoro już wiemy po co są zmienne, to teraz pozostaje pytanie jak je wykorzystywać. Pozostańmy przy porównaniu zmiennych do pudełek. \n"
"W takim razie aby coś z pudełka wyciągnąć, trzeba najpierw coś włożyć do środka. Wykorzystamy do tego znak \"=\". \n"
"A więc kod, który miałby przypisać do zmiennej myInt wartość 4 będzie wyglądał następująco:\n"
"myInt = 4\n"
"myInt - nazwa zmiennej, którą później możemy wykorzystać\n"
"4 - obecna wartość zmiennej\n"
"Aby przechowywać tekst w zmiennej musimy otoczyć do cudzysłowem \"Jakiś tekst\":\n"
"myString = \"hello\""))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_set_value), _translate("MainWindow", "Wkładanie do pudełka"))
        self.TextEditGetValue.setPlainText(_translate("MainWindow", "Skoro już zapisaliśmy jakąś wartość, to teraz pora na skorzystanie z niej. Nie może być nic prostszego. \n"
"Wystarczy napisać jej nazwę i tylko tyle! Np.\n"
"wiek\n"
"I za pomocą tej prostej komendy możemy dostać się do tego, co skrywało się w pudełku (zmiennej) o nazwie wiek. Teraz pozostaje tylko pytanie, co dokładnie możemy z tą wartością zrobić, gdyż samo wyciągnięcie z pudełka jej nam za dużo nie pomoże. \n"
"1. Możemy pokazać w konsoli jej zawartość dzięki funkcji print: print(wiek)\n"
"2. Możemy dodać ją do innej wartości: wiek + 5\n"
"3. Możemy wykorzystać ją w dowolnym miejscu programu, gdzie normalnie mielibyśmy wykorzystać jej wartość"))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_get_value), _translate("MainWindow", "Wyciąganie z pudełka"))
        self.pushButtonReady1.setText(_translate("MainWindow", "Gotowe"))
        self.lineEditExercise1.setPlaceholderText(_translate("MainWindow", "Wpisz działanie"))
        self.TextEditExercise1.setPlainText(_translate("MainWindow", "Pierwsze zadanie!\n"
"Każdy z poniższych przycisków to zmienna o określonej nazwie. Przenieś na nie tekst z odpowiednimi wartościami, a następnie naciśnij przycisk \"Gotowe\"."))
        self.pushButtonGrunwald.setText(_translate("MainWindow", "bitwa_pod_grunwaldem_rok"))
        self.pushButtonPanTadeusz.setText(_translate("MainWindow", "pan_tadeusz_autor_nazwisko"))
        self.pushButtonStolicaPolski.setText(_translate("MainWindow", "stolica_polski"))
        self.pushButtonProgramowanie.setText(_translate("MainWindow", "czy_programowanie_fajne"))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_exercise1), _translate("MainWindow", "Zadanie 1"))
        self.TextEditExercise2.setPlainText(_translate("MainWindow", "Drugie zadanie!\n"
"Spróbuj za pomocą wiedzy poznanej we wcześniejszych rozdziałach i wiedy o zmiennych, sprawdzić co kryje się pod zmienną o nazwie niespodzianka. Wynik wyświetlić się powinien w konsoli."))
        self.pushButtonRunExercise2.setText(_translate("MainWindow", "Uruchom"))
        self.tabWidgetVariables.setTabText(self.tabWidgetVariables.indexOf(self.tab_exercise2), _translate("MainWindow", "Zadanie 2"))
import obrazki.obrazki_orders
import obrazki.obrazki_variables

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
